id: P58C12CDC
initial_creation_type: ocr
source_metadata:
  volumes:
    c7a4b382856f4101afcda578872b3cb3:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: འཇིག་རྟེན་གསུམ་ལས་རྣམ་པར་རྒྱལ་བ་འཕགས་མ་སྒྲོལ་མ་སྒྲུབ་པའི་ཐབས།
      total_pages: 1712
      volume_number: 42
